### ISSUE TITLE
Allow character substitution for link text in label (#11) is not merged into master?

### ISSUE THREAD

**Issue by webdev2027** [tritum/form_element_linked_checkbox#14]
Hi there. could you check this out, please?
https://stackoverflow.com/questions/59651342/typo3-extform-checkbox-label-with-link-inside
I've install the extension via `composer request tritum/form-element-linked-checkbox`  in jan 2020, but the feature will not working. I thought, you've merged into master in dec 2019 with  the following feature: https://github.com/tritum/form_element_linked_checkbox/pull/11 (I've told with elias via slack about this topic).

Maybe I have an incorrect configuration!? Did I forget something? It's pretty easy ..?! Thanks.

**Comment by tritum** [comment]
This is only in master. No version has been tagged. Could you do me a favor please? Use the current master and try it out. Please come back to me if everything works fine. As soon as you are giving me a thumbs up, I will release version 2.0 and tag it appropriately. Thx!

**Comment by webdev2027** [comment]
Now I've download/clone the whole tritium/form_element_linked_checkbox-master and upload it. 
Clear Cache.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'TRITUM\FormElementLinkedCheckbox\Hooks\FormElementLinkResolverHook' not found | Error thrown in file /.../reno/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3675. Requested URL: http://reno.webseiten.cc/kontakt

**Comment by tucBa** [comment]
Hi. I'm using Typo3 9.5.13 with composer.json require "tritum/form-element-linked-checkbox": "dev-master". Works all fine.
![tritum](https://user-images.githubusercontent.com/60128164/72782044-1a3dc880-3c23-11ea-9761-1ad498bfdc7e.png)

**Comment by webdev2027** [comment]
Hi guys. Sorry, I forgot the `'  '` at the labelText.  Now it works ...

```
      -
        type: LinkedCheckbox
        identifier: linkedcheckbox-1
        label: ' Ja, ich habe die %s gelesen und bin mit der Verarbeitung meiner Daten einverstanden.'
        properties:
          pageUid: '17'
          linkText: 'Datenschutzhinweise'
          elementDescription:
          fluidAdditionalAttributes:
            required: required
        validators:
          -
            identifier: NotEmpty
```
