### ISSUE TITLE
multiple link substitution doesn't work (anymore) in v11

### ISSUE THREAD

**Issue by mtness** [tritum/form_element_linked_checkbox#42]
it seems that the multiple link substitution doesn't work (anymore) in v11 -

I get the error:

`Argument 1 passed to TYPO3\CMS\Form\Domain\Model\Renderable\AbstractRenderable::setLabel() must be of the type string, bool given, called in /var/www/public/typo3conf/ext/form_element_linked_checkbox/Classes/Hooks/FormElementLinkResolverHook.php on line 117`

I tested with your exact example :
```
type: LinkedCheckbox
identifier: consent
label: 'I accept the %s and %s.'
properties:
  pageUid: '3'
  linkText: 'terms and conditions'
  additionalLinks:
    4: 'privacy policy'
```

On top of this, I wonder how to translate the link title of the additional link?

Thanks in advance and best regards,
MT
