### ISSUE TITLE
feature request: short label

### ISSUE THREAD

**Issue by bh-teufels** [tritum/form_element_linked_checkbox#47]
it would be great to have a "short label" Field so with the use of variant it would be possible to have the (long) label in form and for finishers and summary having a short label 

label: 
`I agree that my sent data will be processed for the purpose of processing my request. For more information, see our %s`

short-label:
`%s accepted`

**Comment by pascualet** [comment]
That sounds good, I would be interested in the solution.
How did you override the Partial for rendering a short label for the email?

**Comment by bh-teufels** [comment]
i override the EmailToReceiver and EmailToSender Finisher and put the 2 different translations from my own language files into variables

```
<f:variable name="shortlabel" value="{formvh:translateElementProperty(element: formValue.element, property: 'shortlabel') -> f:format.stripTags(allowedTags: '<a>')}" />
<f:variable name="label" value="{formvh:translateElementProperty(element: formValue.element, property: 'label') -> f:format.stripTags(allowedTags: '<a>')}" />

[...]


<td valign="top" align="left"><f:format.html>{f:if(condition: '{shortlabel}', then: '{shortlabel}', else: '{label}')}</f:format.html</td>
```

**Comment by pascualet** [comment]
... ok, so far so good, that was what I was wondering: if there wouldn't be any need to override finishers.
Because I was trying that, but I haven't found the solution how to change the finishers.
A solution only via adjusting yaml seems not possible.

```
variants:
  - identifier: linkedcheckbox-1
    condition: 'finisherIdentifier == "EmailToReceiver"'
    renderingOptions:
      label: 'short label'
      enabled: true
```
