### ISSUE TITLE
No %s substitution in variants

### ISSUE THREAD

**Issue by tgriessbach** [tritum/form_element_linked_checkbox#61]
Hello all,
my system is 
TYPO3 11.5 
PHP 8.1 
form_element_linked_checkbox 4.0.0

I have the following yaml configuration:

```
renderables:
  - identifier: gdpr
	type: LinkedCheckbox
	label: 'Ich stimme zu... Ich habe die %s zur Kenntnis genommen...'
	properties:
	  pageUid: 236
	  linkText: 'Datenschutzerklärung'
	  fluidAdditionalAttributes:
		required: required
	variants:
	  - identifier: gdpr-en
		condition: 'siteLanguage("locale") == "en_US.UTF-8"'
		label: 'I agree that my data... I have taken note of the %s, in particular...'
		properties:
		  pageUid: 236
		  linkText: 'privacy policy'
```

In the default Language (here german) the `%s` is substituted correctly.
But in the translation variant the label is shown unchanged: 
> I agree that my data... I have taken note of the %s, in particular...

So translation works but not the substitution.
Is my configuration wrong?
The target page has an active translation, so the link building shoud not be the issue.

I tested form_element_linked_checkbox v3.0.0 and it has the same problem.

**Comment by chrisi51** [comment]
Hey @tgriessbach 
i do the following:
```
identifier: kontakt
renderables:
  -
    renderables:
      -
        properties:
          linkText: 'privacy policy'
          fluidAdditionalAttributes:
            required: required
        type: LinkedCheckbox
        identifier: privacypolicy
        label: 'I have read and agree the %s.'
```
and having languages files with such a content:
```
      <trans-unit id="kontakt.element.privacypolicy.properties.label">
          <source>I have read and agree the %s.</source>
          <target>Ich habe die %s gelesen und bin damit einverstanden.</target>
      </trans-unit>
```
