### ISSUE TITLE
Reverts templateVariant to version1

### ISSUE THREAD

**Issue by createdwithlove** [tritum/form_element_linked_checkbox#64]
In TYPO3 v12 the extension seems to break with the `templateVariant: version2`.

In a sitepackage with the following form configuration
```
prototypes:
    standard:
        formElementsDefinition:
            Form:
                renderingOptions:
                    templateVariant: version2
```
the new templates/partials (FrontendVersion1) are used.

As soon as you add `setup.typoscript` from `EXT:form_element_linked_checkbox` (no matter before or after the sitepackage ), the old templates and partials are displayed.
