### ISSUE TITLE
make use use version-2-template (need help)

### ISSUE THREAD

**Issue by wini2** [tritum/form_element_linked_checkbox#83]
According to #64 it seems not possible to use version-2-templates. 

I stored the form-templates in sitepackage an adapted the summery-page to my needs, but linked_checkbox breaks it. Unfortunately in #64 it's not explained how to make use of template-version 2. Trying to alter the path to 

plugin.tx_form {
  settings {
    yamlConfigurations {
      1505042806 = EXT:myownsitepackage/Resources/ext/form-element-linked-checkbox/Configuration/Yaml/FormSetup.yaml
    }
  }
}

and in the FormSetup.yaml to my outsources files
          partialRootPaths:
           # 1505042806: 'EXT:form_element_linked_checkbox/Resources/Private/Frontend/Partials/'
            1505042806: 'EXT:myownsitepackage/Resources/ext/form-element-linked-checkbox/Resources/Private/Frontend/Partials/'

does not work.

**Comment by Patta** [comment]
@wini2 I just stumbled upon this issue in combination with `EXT:bootstrap_package` which also uses `templateVariant version2`. You also need to override the `LinkedCheckbox.html` partial in your sitepackage and adapt the markup to the templateVariant version2 for proper frontend rendering.

FormSetup.yaml with custom partialRootPaths for templateVariant version2:
```
prototypes:
  standard:
    formElementsDefinition:
      Form:
        variants:
          -
            identifier: template-variant
            condition: 'getRootFormProperty("renderingOptions.templateVariant") == "version2"'
            renderingOptions:
              partialRootPaths:
                30: 'EXT:sitepackage/Resources/Private/Partials/Form/'
```
